version: '3'
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678abc' 
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '12345678abc'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=12345678abc
    ports:
      - 20000:80
  app:
    tty: true
    build: ./backend/
    ports:
      - 20001:3000
    volumes:
      - ./backend/app:/app
