# mutagen compose -f mutagen-compose.yml up
version: '3'
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678abc' 
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '12345678abc'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=12345678abc
    ports:
      - 20000:80
  backend:
    tty: true
    # build: ./backend/
    image: minminzemi1121/laravel-test_backend:latest
    ports:
      - 20001:3000
    volumes:
      - ./backend/app:/app
  frontend:
    tty: true
    # build: ./frontend/
    image: minminzemi1121/laravel-test_frontend:latest
    ports:
      - 20002:3000
    volumes:
      - frontend:/app


volumes:
  frontend:

# https://tech.griphone.co.jp/2020/09/17/accelerate-docker-with-mutagen/
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    frontend:
      alpha: "./frontend/app"
      beta: "volume://frontend"
      mode: "two-way-resolved"
      ignore:
        paths:
      configurationBeta:
        permissions:
          defaultFileMode: 0666
          defaultDirectoryMode: 0777
