SET GLOBAL sql_mode = 'ALLOW_INVALID_DATES';
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

DROP DATABASE IF EXISTS `app`;
CREATE DATABASE `app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


DROP DATABASE IF EXISTS `test_app`;
CREATE DATABASE `test_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;



COMMIT;
