name: Testing on stg 

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    branches: 
      - "master"

env:
  MYENV: test 
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with docker-compose stack
        run: |
          cd ${GITHUB_WORKSPACE}
          echo "----host------"
          ls -alt ./ 
          echo "----------"
          docker-compose up -d --remove-orphans db app
          echo "----container------"
          docker-compose exec -T -w /app app ls -alt ./ 
          echo "----------"
          docker-compose exec -T -w /app app composer install 
          docker-compose exec -T -w ${GITHUB_WORKSPACE} app vendor/bin/phpunit 
